export type GuidanceClassification =
  | "Legislation"
  | "Approved Code of Practice"
  | "Official guidance"
  | "Industry guidance"
  | "British Standard / best practice";

export interface ComplianceGuidance {
  track: string;
  title: string;
  classification: GuidanceClassification;
  jurisdiction: string;
  applicability: string;
  owner: string;
  url: string;
  reviewedAt: string;
  reviewNote: string;
}

export type ComplianceGapPriority = "high" | "medium" | "low";

export interface ComplianceGap {
  id: string;
  priority: ComplianceGapPriority;
  tracks: string[];
  title: string;
  rationale: string;
  recommendedControl: string;
}

/**
 * Public, authoritative signposts only. Standards are referenced by title and
 * never reproduced because their text is licensed and risk controls must be
 * selected for the particular premises.
 *
 * The register is a signposting and review aid, not a statement that any
 * customer is compliant. Source applicability, legal effect and review dates
 * must be checked by the responsible person and a qualified UK adviser.
 */
export const GUIDANCE_REVIEWED_AT = "2026-08-29";

export const UK_COMPLIANCE_GUIDANCE: ComplianceGuidance[] = [
  {
    track: "All tracks",
    title: "Health and Safety at Work etc. Act 1974",
    classification: "Legislation",
    jurisdiction: "Great Britain; Northern Ireland has a separate primary framework",
    applicability: "Employers, self-employed people and duty holders where the undertaking may affect workers or others.",
    owner: "Employer / duty holder",
    url: "https://www.legislation.gov.uk/ukpga/1974/37/contents",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Use with the law and regulator guidance for the nation, premises and activity. Records do not certify compliance.",
  },
  {
    track: "All tracks",
    title: "Management of Health and Safety at Work Regulations 1999",
    classification: "Legislation",
    jurisdiction: "England, Wales and Scotland; Northern Ireland has equivalent 2000 Regulations",
    applicability: "Suitable and sufficient risk assessment, competent assistance, preventive arrangements, information, training and emergency procedures.",
    owner: "Employer / responsible person",
    url: "https://www.legislation.gov.uk/uksi/1999/3242/contents",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Review after material change, an incident or when controls are no longer effective; do not turn a generic checklist frequency into a legal rule.",
  },
  {
    track: "All tracks",
    title: "Management of Health and Safety at Work Regulations (Northern Ireland) 2000",
    classification: "Legislation",
    jurisdiction: "Northern Ireland",
    applicability: "Northern Ireland employers and duty holders, alongside HSENI guidance.",
    owner: "Employer / responsible person",
    url: "https://www.legislation.gov.uk/nisr/2000/388/contents",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Do not present Great Britain regulations as directly applicable in Northern Ireland; retain the nation in the client profile.",
  },
  {
    track: "FireTrack",
    title: "Fire safety in the workplace",
    classification: "Official guidance",
    jurisdiction: "England and Wales; fire regimes differ in Scotland and Northern Ireland",
    applicability: "Responsible persons for most non-domestic premises under the applicable national fire-safety regime.",
    owner: "Responsible person / premises manager",
    url: "https://www.gov.uk/workplace-fire-safety-your-responsibilities",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Maintain a suitable fire risk assessment, emergency arrangements, competent maintenance and evidence. Alarm, light, door and drill intervals must follow the assessment and system guidance.",
  },
  {
    track: "FireTrack",
    title: "Non-domestic fire safety",
    classification: "Official guidance",
    jurisdiction: "Scotland",
    applicability: "Most non-domestic premises under the Fire (Scotland) Act 2005 and Fire Safety (Scotland) Regulations 2006.",
    owner: "Responsible person / duty holder",
    url: "https://www.gov.scot/policies/fire-and-rescue/non-domestic-fire-safety/",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Use Scottish premises guidance and the appropriate risk assessment form; do not reuse England and Wales wording without checking scope.",
  },
  {
    track: "KitchenTrack",
    title: "Food safety management systems using HACCP principles",
    classification: "Official guidance",
    jurisdiction: "UK food businesses; implementation and regulator material varies by nation",
    applicability: "Food businesses must operate food-safety procedures based on HACCP principles or an appropriate documented system.",
    owner: "Food business operator / food safety lead",
    url: "https://www.food.gov.uk/business-guidance/hazard-analysis-and-critical-control-point-haccp",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Record the operation-specific hazards, critical limits, monitoring, corrective action and verification. Example temperature values are not universal substitutes for the HACCP system.",
  },
  {
    track: "KitchenTrack",
    title: "Safer Food, Better Business",
    classification: "Official guidance",
    jurisdiction: "England and Wales; use CookSafe or Northern Ireland material where applicable",
    applicability: "Practical food-safety-management pack for relevant small food businesses.",
    owner: "Food business operator / kitchen manager",
    url: "https://www.food.gov.uk/business-guidance/safer-food-better-business-sfbb",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Use as a signpost and adapt it to the actual business, menu, process and documented HACCP controls.",
  },
  {
    track: "KitchenTrack",
    title: "Food business hygiene guidance",
    classification: "Official guidance",
    jurisdiction: "Scotland",
    applicability: "Scottish food businesses, including the CookSafe and 4Cs approach.",
    owner: "Food business operator / food safety lead",
    url: "https://www.foodstandards.gov.scot/business-guidance/running-a-food-business/food-hygiene",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Use Food Standards Scotland material for Scottish operations and preserve the business-specific record of controls.",
  },
  {
    track: "KitchenTrack",
    title: "Food Hygiene Regulations (Northern Ireland) 2006",
    classification: "Legislation",
    jurisdiction: "Northern Ireland",
    applicability: "Northern Ireland food businesses, subject to amendments and local enforcement.",
    owner: "Food business operator",
    url: "https://www.daera-ni.gov.uk/publications/food-hygiene-regulations-ni-2006-amended",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Use DAERA/food regulator material for Northern Ireland rather than presenting the FSA England and Wales pack as universal.",
  },
  {
    track: "LegionellaTrack",
    title: "Legionnaires' disease: The control of legionella bacteria in water systems (L8)",
    classification: "Approved Code of Practice",
    jurisdiction: "Great Britain; confirm Northern Ireland arrangements with HSENI",
    applicability: "Duty holders responsible for work or premises water systems where legionella risk may arise.",
    owner: "Responsible person / competent water specialist",
    url: "https://www.hse.gov.uk/pubns/books/l8.htm",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Maintain a risk assessment, written scheme, competent appointments, monitoring and remedial evidence. L8 is not a universal calendar or test prescription.",
  },
  {
    track: "LegionellaTrack",
    title: "Legionnaires' disease: Technical guidance HSG274",
    classification: "Official guidance",
    jurisdiction: "Great Britain; use applicable devolved/NI regulator guidance",
    applicability: "Technical control guidance for hot and cold water systems, evaporative cooling and other specified systems.",
    owner: "Competent water specialist / responsible person",
    url: "https://www.hse.gov.uk/pubns/books/hsg274.htm",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "The system type, risk assessment and written scheme determine monitoring and action; retain readings, actions, evidence and verification.",
  },
  {
    track: "AquaTrack / PoolTrack",
    title: "Health and safety in swimming pools (HSG179)",
    classification: "Official guidance",
    jurisdiction: "Great Britain; check local licensing and devolved requirements",
    applicability: "Swimming-pool operators and duty holders managing bather, plant, chemical and emergency risks.",
    owner: "Pool operator / competent pool manager",
    url: "https://www.hse.gov.uk/pubns/books/hsg179.htm",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Pool operating procedures, water-treatment ranges, supervision and emergency arrangements must be specific to the installation and bather risk.",
  },
  {
    track: "AquaTrack / PoolTrack",
    title: "Pool Water Treatment Advisory Group guidance",
    classification: "Industry guidance",
    jurisdiction: "UK industry guidance; confirm local authority and nation-specific requirements",
    applicability: "Operational good practice for pool-water treatment, testing, records and incident response.",
    owner: "Pool operator / water-treatment specialist",
    url: "https://www.pwtag.org/",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Use alongside HSG179, the site's written operating procedures and competent water-treatment advice; do not label industry values as legislation.",
  },
  {
    track: "TubTrack / HotTubTrack",
    title: "The control of legionella and other infectious agents in spa-pool systems (HSG282)",
    classification: "Official guidance",
    jurisdiction: "Great Britain; confirm Northern Ireland and local authority requirements",
    applicability: "Spa-pool and hot-tub operators, including venues offering spa-pool facilities to the public.",
    owner: "Spa-pool operator / competent water specialist",
    url: "https://www.hse.gov.uk/pubns/books/hsg282.htm",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Use a site-specific risk assessment, written scheme, competent review, testing, closure and incident controls; values and frequencies are not blanket legal defaults.",
  },
  {
    track: "PATtrack",
    title: "Maintaining portable and transportable electrical equipment (INDG236)",
    classification: "Official guidance",
    jurisdiction: "Great Britain; use HSENI guidance for Northern Ireland",
    applicability: "Employers and duty holders responsible for portable or transportable electrical equipment.",
    owner: "Duty holder / electrical competent person",
    url: "https://www.hse.gov.uk/pubns/indg236.htm",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Inspection and testing should follow risk, equipment, environment and use. There is no universal legal requirement for annual PAT testing; record quarantine, repair and retest.",
  },
  {
    track: "PATtrack",
    title: "Electricity at Work Regulations 1989",
    classification: "Legislation",
    jurisdiction: "Great Britain; Northern Ireland has corresponding regulations",
    applicability: "Electrical systems and equipment used at work where danger may arise.",
    owner: "Employer / person responsible for electrical systems",
    url: "https://www.legislation.gov.uk/uksi/1989/635/contents",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "PAT records support, but do not replace, suitable maintenance, competence and safe systems of work.",
  },
  {
    track: "IncidentTrack",
    title: "Reporting of Injuries, Diseases and Dangerous Occurrences (RIDDOR)",
    classification: "Official guidance",
    jurisdiction: "Great Britain; Northern Ireland has separate reporting regulations",
    applicability: "Responsible persons deciding whether a work-related death, injury, disease or dangerous occurrence is reportable.",
    owner: "Responsible person / incident lead",
    url: "https://www.hse.gov.uk/riddor/",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "The product must preserve the investigation and reportability decision but must not decide RIDDOR status automatically. Record report references and statutory timing.",
  },
  {
    track: "PremisesTrack",
    title: "Workplace health, safety and welfare (L24)",
    classification: "Official guidance",
    jurisdiction: "Great Britain; check Northern Ireland workplace regulations",
    applicability: "Workplace duty holders responsible for safe access, lighting, ventilation, temperature, sanitary facilities, cleanliness and welfare.",
    owner: "Employer / premises manager",
    url: "https://www.hse.gov.uk/pubns/books/l24.htm",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Use proportionate premises inspections and actions based on the actual workplace, users and risks; no generic inspection interval is universally statutory.",
  },
  {
    track: "TreeTrack",
    title: "Managing risks from trees",
    classification: "Official guidance",
    jurisdiction: "Great Britain; confirm devolved land-management requirements",
    applicability: "Landowners and managers where trees could affect people, property, roads or work activities.",
    owner: "Landowner / tree duty holder / arboricultural specialist",
    url: "https://www.hse.gov.uk/treework/",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Inspection and remedial work should be risk-based and competent; BS 3998 is a paid best-practice standard, not an annual legal rule.",
  },
  {
    track: "TreeTrack",
    title: "Tree work recommendations (BS 3998)",
    classification: "British Standard / best practice",
    jurisdiction: "UK industry best practice",
    applicability: "Arboricultural work where the responsible person chooses to apply the current standard.",
    owner: "Arboricultural specialist",
    url: "https://knowledge.bsigroup.com/products/tree-work-recommendations",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Reference the standard without reproducing licensed text; record the edition or contractor method used.",
  },
  {
    track: "PestTrack",
    title: "Food hygiene for businesses",
    classification: "Official guidance",
    jurisdiction: "UK food businesses; nation-specific food regulators may add requirements",
    applicability: "Food premises where pest prevention, proofing, monitoring and treatment are part of hygienic operation.",
    owner: "Food business operator / pest-control lead",
    url: "https://www.food.gov.uk/business-guidance/hazard-analysis-and-critical-control-point-haccp",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Pest controls should be linked to the food-safety system and premises risk assessment, with contractor competence and treatment evidence.",
  },
  {
    track: "PestTrack",
    title: "Cleaning effectively in your business",
    classification: "Official guidance",
    jurisdiction: "UK food businesses; check devolved food guidance",
    applicability: "Food businesses designing cleaning, disinfection, equipment and verification controls.",
    owner: "Food business operator / kitchen manager",
    url: "https://www.food.gov.uk/business-guidance/cleaning-effectively-in-your-business",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Cleaning records are evidence of a defined method and verification, not proof that every hazard is controlled.",
  },
  {
    track: "BikeTrack",
    title: "Provision and Use of Work Equipment Regulations (PUWER)",
    classification: "Official guidance",
    jurisdiction: "Great Britain; Northern Ireland has separate work-equipment regulations",
    applicability: "Bicycles and related equipment supplied or used as work equipment, where the legal definition applies.",
    owner: "Employer / work-equipment duty holder",
    url: "https://www.hse.gov.uk/work-equipment-machinery/puwer.htm",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Define checks, maintenance, instructions and competence from how the equipment is actually used; do not imply that a recreational cycle check is automatically a PUWER inspection.",
  },
  {
    track: "FixTrack",
    title: "Managing risks and risk assessment at work",
    classification: "Official guidance",
    jurisdiction: "Great Britain; use HSENI guidance for Northern Ireland",
    applicability: "Workplace hazards and corrective work that do not belong to a more specialised track.",
    owner: "Risk owner / responsible manager",
    url: "https://www.hse.gov.uk/simple-health-safety/risk/",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Record the hazard, people exposed, interim control, owner, due date, evidence and independent verification where needed.",
  },
  {
    track: "DailyTrack AM / DailyTrack PM",
    title: "Management of health and safety at work: risk assessment",
    classification: "Official guidance",
    jurisdiction: "Great Britain; use the Northern Ireland equivalent framework where applicable",
    applicability: "Routine operational checks that evidence a risk control or identifies a finding.",
    owner: "Responsible manager / person completing the check",
    url: "https://www.hse.gov.uk/simple-health-safety/risk/",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Daily frequency is a product workflow, not automatically a statutory requirement; clients must configure it to their risk assessment and operation.",
  },
  {
    track: "RoomTrack",
    title: "Workplace health, safety and welfare (L24)",
    classification: "Official guidance",
    jurisdiction: "Great Britain; check national workplace welfare requirements",
    applicability: "Housekeeping and room-condition records where cleanliness, access, defects or welfare affect workers or guests.",
    owner: "Premises / housekeeping manager",
    url: "https://www.hse.gov.uk/pubns/books/l24.htm",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Clean, tidy and to-standard are operational housekeeping criteria, not legal categories. Define local standards, escalation and evidence for the property.",
  },
  {
    track: "DocTrack",
    title: "What is competence?",
    classification: "Official guidance",
    jurisdiction: "Great Britain; confirm Northern Ireland regulator guidance",
    applicability: "Employers deciding what competence evidence, instruction and supervision a role requires.",
    owner: "Employer / document owner",
    url: "https://www.hse.gov.uk/competence/what-is-competence.htm",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Acknowledgement proves receipt, not understanding or competence. Retain version, audience, acknowledgement and review evidence.",
  },
  {
    track: "SafeTrack",
    title: "First aid at work: Guidance on regulations (L74)",
    classification: "Official guidance",
    jurisdiction: "Great Britain; Northern Ireland has separate first-aid regulations and guidance",
    applicability: "Employers assessing first-aid needs, appointed persons, equipment, training and arrangements.",
    owner: "Employer / first-aid needs assessor",
    url: "https://www.hse.gov.uk/PUBNS/books/l74.htm",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "First-aid provision must follow a documented needs assessment; certificate expiry reminders do not replace adequate cover during shifts and leave.",
  },
  {
    track: "TrainTrack",
    title: "Health and safety training",
    classification: "Official guidance",
    jurisdiction: "Great Britain; use the applicable national regulator",
    applicability: "Employers who need workers to have information, instruction, training, supervision and role competence.",
    owner: "Employer / training owner",
    url: "https://www.hse.gov.uk/training/",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Refresher periods should be based on role, risk, competence and change; no single universal training expiry applies to every subject.",
  },
  {
    track: "GreenTrack",
    title: "Health and safety in landscaping and horticulture",
    classification: "Official guidance",
    jurisdiction: "Great Britain; confirm devolved agriculture and pesticide requirements",
    applicability: "Grounds, horticulture, landscaping and maintenance activities involving machinery, chemicals, manual handling or contractors.",
    owner: "Grounds manager / employer",
    url: "https://www.hse.gov.uk/agriculture/",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Use activity-specific risk assessments, competent operators, equipment maintenance, pesticide controls where relevant and contractor evidence.",
  },
  {
    track: "SwimTrack",
    title: "Health and safety in swimming pools (HSG179)",
    classification: "Official guidance",
    jurisdiction: "Great Britain; check devolved/local pool requirements",
    applicability: "Swimming activity, supervision, rescue, water quality, plant, chemicals and emergency arrangements.",
    owner: "Pool operator / swimming manager",
    url: "https://www.hse.gov.uk/pubns/books/hsg179.htm",
    reviewedAt: GUIDANCE_REVIEWED_AT,
    reviewNote: "Pool supervision and water checks must be tied to the site's operating plan, bather load, plant and emergency risk assessment.",
  },
];

export const UK_COMPLIANCE_GAPS: ComplianceGap[] = [
  {
    id: "nation-specific-fire-and-incident",
    priority: "high",
    tracks: ["FireTrack", "IncidentTrack"],
    title: "Confirm nation-specific fire and incident workflows",
    rationale: "Fire and incident reporting frameworks differ between Great Britain and Northern Ireland, and fire duties also differ within Great Britain.",
    recommendedControl: "Keep the client's nation visible at the point of guidance and require the responsible person to confirm the applicable fire regime and RIDDOR-equivalent reporting route.",
  },
  {
    id: "accountability-by-site",
    priority: "high",
    tracks: ["All tracks"],
    title: "Add site-level accountability and applicability review",
    rationale: "A client can operate multiple premises with different activities, risks, competent people and local requirements.",
    recommendedControl: "Capture responsible person, operation type, competent appointments, source applicability and next review at site level where one client has materially different premises.",
  },
  {
    id: "food-business-controls",
    priority: "high",
    tracks: ["KitchenTrack", "PestTrack"],
    title: "Complete operation-specific food controls",
    rationale: "Generic diary fields cannot demonstrate a business-specific HACCP system, allergen controls, cleaning verification or pest controls on their own.",
    recommendedControl: "Link records to a reviewed HACCP/CookSafe/SFBB system, critical limits, allergen controls, corrective action and verification evidence.",
  },
  {
    id: "water-written-scheme",
    priority: "high",
    tracks: ["LegionellaTrack", "AquaTrack / PoolTrack", "TubTrack / HotTubTrack", "SwimTrack"],
    title: "Require written-scheme and competent-person confirmation",
    rationale: "Water systems and pool/spa risks depend on the installation, users, plant and risk assessment; fixed intervals and values are not universal law.",
    recommendedControl: "Require a current written-scheme or operating-plan reference, named competent reviewer, site-specific limits and evidence of action when controls fall outside the plan.",
  },
  {
    id: "risk-based-equipment",
    priority: "medium",
    tracks: ["PATtrack", "BikeTrack", "GreenTrack", "FixTrack"],
    title: "Record the risk basis for equipment checks",
    rationale: "PAT, PUWER, machinery and grounds controls depend on equipment, environment, use and competence rather than a universal calendar.",
    recommendedControl: "Store the inspection rationale, competent person, quarantine/repair/retest trail and review trigger instead of presenting annual checks as law.",
  },
  {
    id: "contractor-competence",
    priority: "medium",
    tracks: ["FireTrack", "LegionellaTrack", "TreeTrack", "GreenTrack", "PremisesTrack", "FixTrack"],
    title: "Strengthen contractor competence and coordination evidence",
    rationale: "Using a contractor does not transfer the duty holder's responsibility for scope, competence, coordination or close-out.",
    recommendedControl: "Capture appointment scope, competence evidence, method/permit references, site induction, coordination and independent close-out verification.",
  },
  {
    id: "people-records-privacy",
    priority: "medium",
    tracks: ["DocTrack", "SafeTrack", "TrainTrack", "IncidentTrack"],
    title: "Validate retention and access for people records",
    rationale: "Training, incident, health, safeguarding and employment records can contain personal or sensitive data and do not share one universal retention period.",
    recommendedControl: "Apply client retention schedules, role-based access, a lawful basis and review/deletion process; distinguish acknowledgement from competence.",
  },
  {
    id: "operational-local-standards",
    priority: "low",
    tracks: ["DailyTrack AM / DailyTrack PM", "RoomTrack"],
    title: "Make local operational standards explicit",
    rationale: "Daily and housekeeping checks are useful evidence but their frequency and pass criteria come from the property's risk assessment and operating standards.",
    recommendedControl: "Let managers record the local standard, review trigger, owner, exception handling and evidence required when a check is incomplete or not to standard.",
  },
];