import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AppLayout } from "@/components/layout";
import { LegacyPATRegister } from "@/components/pat-track/legacy-register";
import { failureLocationDisplay, failureUpdateBody, mapFailure, type Failure } from "@/components/pat-track/failure-location";
import { mapReplacement, replacementIdentityNote, type Replacement } from "@/components/pat-track/replacement-identity";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { useToast } from "@/hooks/use-toast";
import { useCanAdmin, useCanEdit } from "@/context/auth-context";
import { AlertTriangle, CheckCircle2, ClipboardList, FileText, Library, Loader2, Pencil, Plus, Trash2, Wrench, Zap } from "lucide-react";
import { beginApiMutation } from "@/lib/api";

const baseUrl = import.meta.env.BASE_URL?.replace(/\/$/, "") ?? "";

type TemplateItem = { id?: number; name: string; applianceType?: string; quantity?: number };
type Site = { id: number; name: string };
type EquipmentTemplate = { id: number; name: string; description?: string | null; siteId?: number | null; items?: TemplateItem[] };
type Room = { id: number; siteId?: number; roomNumber: string; area?: string | null; templateId?: number | null; templateName?: string | null; testIntervalMonths?: number | null; replacements?: Replacement[] };
type Certificate = { id: number; siteId?: number; testDate: string; contractor: string; certificateRef: string; coveredRoomIds: number[]; coveredRooms: { id: number; name: string | null; snapshotSource?: string | null }[]; coveredAreas?: string | null; appliancesTested: number; passCount: number; failCount: number; nextTestDue?: string | null; documentId?: number | null; documentUrl?: string | null };
type Overdue = { id?: number; roomId?: number; roomNumber?: string; area?: string; status?: "untested" | "overdue"; lastTestDate?: string | null; nextTestDue?: string | null; daysOverdue?: number };

async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const mutationSucceeded = beginApiMutation(init?.method, `/pat-track${path}`);
  const response = await fetch(`${baseUrl}/api/pat-track${path}`, { credentials: "include", ...init, headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) } });
  if (!response.ok) {
    const body = await response.json().catch(() => null);
    throw new Error(body?.error ?? body?.message ?? `Request failed (${response.status})`);
  }
  mutationSucceeded();
  return response.json();
}
async function rootApi<T>(path: string): Promise<T> {
  const response = await fetch(`${baseUrl}/api${path}`, { credentials: "include" });
  if (!response.ok) throw new Error(`Request failed (${response.status})`);
  return response.json();
}
const key = (name: string) => ["pat-track", name];
const fmt = (value?: string | null) => value ? new Date(`${value.slice(0, 10)}T12:00:00`).toLocaleDateString("en-GB") : "—";
const readArray = <T,>(data: T[] | { items?: T[]; data?: T[] } | undefined) => Array.isArray(data) ? data : data?.items ?? data?.data ?? [];
const mapTemplate = (x: any): EquipmentTemplate => ({ id: x.id, name: x.name, description: x.description, siteId: x.site_id ?? x.siteId ?? null, items: x.items ?? [] });
const mapRoom = (x: any, replacements: any[] = []): Room => ({ id: x.id, siteId: x.site_id, roomNumber: x.name, area: x.area_type, templateId: x.template_id, templateName: x.template_name, testIntervalMonths: x.test_interval_months, replacements: replacements.filter(r => r.room_id === x.id).map(mapReplacement) });
const mapCertificate = (x: any): Certificate => ({ id: x.id, siteId: x.site_id, testDate: x.visit_date, contractor: x.contractor_name ?? "", certificateRef: x.certificate_ref, coveredRoomIds: (x.rooms ?? []).map((r: any) => r.id), coveredRooms: (x.rooms ?? []).map((r: any) => ({ id: r.id, name: r.name ?? null, snapshotSource: r.snapshot_source ?? null })), coveredAreas: x.notes, appliancesTested: x.appliances_tested_count ?? 0, passCount: x.pass_count ?? 0, failCount: x.fail_count ?? 0, nextTestDue: x.next_test_due, documentId: x.document_id, documentUrl: x.document_link });

function ErrorState({ error }: { error: unknown }) {
  return <div className="rounded-sm border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800" data-testid="status-pat-error">Unable to load this register: {error instanceof Error ? error.message : "Unknown error"}</div>;
}
function Empty({ children }: { children: string }) {
  return <div className="border border-dashed rounded-sm px-5 py-10 text-center text-sm text-muted-foreground">{children}</div>;
}
function Loading() { return <div className="flex justify-center p-12 text-muted-foreground"><Loader2 className="h-5 w-5 animate-spin" /></div>; }
function Status({ resolved }: { resolved?: string | null }) {
  return <Badge className={resolved ? "bg-emerald-100 text-emerald-800 border-emerald-200 rounded-sm" : "bg-rose-100 text-rose-800 border-rose-200 rounded-sm"}>{resolved ? "Resolved" : "Open"}</Badge>;
}

function TemplateDialog({ open, close, value, sites, selectedSiteId, saved }: { open: boolean; close: () => void; value?: EquipmentTemplate | null; sites: Site[]; selectedSiteId: string; saved: () => void }) {
  const { toast } = useToast(); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [siteId, setSiteId] = useState(""); const [items, setItems] = useState<TemplateItem[]>([]);
  useEffect(() => { if (open) { setName(value?.name ?? ""); setDescription(value?.description ?? ""); setSiteId(value?.siteId ? String(value.siteId) : selectedSiteId); setItems(value?.items?.length ? value.items : [{ name: "", applianceType: "Other", quantity: 1 }]); } }, [open, value, selectedSiteId]);
  const mutation = useMutation({ mutationFn: () => api(value ? `/equipment-templates/${value.id}` : "/equipment-templates", { method: value ? "PUT" : "POST", body: JSON.stringify({ siteId: siteId ? Number(siteId) : null, name: name.trim(), description: description.trim() || null, active: true, items: items.filter(i => i.name.trim()).map(i => ({ name: i.name.trim(), applianceType: i.applianceType ?? "Other", quantity: Number(i.quantity) || 1 })) }) }), onSuccess: () => { toast({ title: value ? "Template updated" : "Template created" }); saved(); close(); }, onError: (e: Error) => toast({ title: "Unable to save template", description: e.message, variant: "destructive" }) });
  return <Dialog open={open} onOpenChange={v => !v && close()}><DialogContent className="max-w-xl max-h-[90vh] overflow-y-auto rounded-sm"><DialogHeader><DialogTitle>{value ? "Edit equipment template" : "New equipment template"}</DialogTitle></DialogHeader><div className="space-y-4"><div><Label>Site</Label><select className="mt-1 flex h-10 w-full rounded-sm border border-input bg-background px-3 text-sm" value={siteId} onChange={e => setSiteId(e.target.value)}><option value="">All sites (global template)</option>{sites.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div><Label>Name *</Label><Input data-testid="input-template-name" className="mt-1" value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Standard guest room" /></div><div><Label>Description</Label><Input className="mt-1" value={description} onChange={e => setDescription(e.target.value)} /></div><div><Label>Standard appliances</Label><div className="mt-2 space-y-2">{items.map((item, index) => <div key={index} className="flex gap-2"><Input value={item.name} onChange={e => setItems(v => v.map((x, i) => i === index ? { ...x, name: e.target.value } : x))} placeholder="Appliance name" /><Input className="w-32" type="number" min="1" value={item.quantity ?? 1} onChange={e => setItems(v => v.map((x, i) => i === index ? { ...x, quantity: Number(e.target.value) } : x))} /><Button data-testid={`button-remove-template-item-${index}`} variant="ghost" size="icon" onClick={() => setItems(v => v.filter((_, i) => i !== index))}><Trash2 className="h-4 w-4" /></Button></div>)}</div><Button data-testid="button-add-template-item" variant="outline" size="sm" className="mt-2" onClick={() => setItems(v => [...v, { name: "", applianceType: "Other", quantity: 1 }])}><Plus className="mr-1 h-3.5 w-3.5" />Add appliance</Button></div></div><DialogFooter><Button variant="outline" onClick={close}>Cancel</Button><Button data-testid="button-save-template" disabled={!name.trim() || mutation.isPending} onClick={() => mutation.mutate()}>{mutation.isPending ? "Saving…" : "Save template"}</Button></DialogFooter></DialogContent></Dialog>;
}

function RoomDialog({ open, close, value, templates, sites, selectedSiteId, saved }: { open: boolean; close: () => void; value?: Room | null; templates: EquipmentTemplate[]; sites: Site[]; selectedSiteId: string; saved: () => void }) {
  const { toast } = useToast(); const [form, setForm] = useState({ siteId: "", roomNumber: "", area: "", templateId: "", testIntervalMonths: "12" });
  useEffect(() => { if (open) setForm({ siteId: value?.siteId ? String(value.siteId) : selectedSiteId, roomNumber: value?.roomNumber ?? "", area: value?.area ?? "", templateId: value?.templateId ? String(value.templateId) : "", testIntervalMonths: String(value?.testIntervalMonths ?? 12) }); }, [open, value, selectedSiteId]);
  const mutation = useMutation({ mutationFn: () => api(value ? `/rooms/${value.id}` : "/rooms", { method: value ? "PUT" : "POST", body: JSON.stringify({ siteId: Number(form.siteId), name: form.roomNumber.trim(), areaType: form.area.trim() || "room", templateId: form.templateId ? Number(form.templateId) : null, testIntervalMonths: Number(form.testIntervalMonths) || 12, active: true, notes: null }) }), onSuccess: () => { toast({ title: value ? "Room updated" : "Room added" }); saved(); close(); }, onError: (e: Error) => toast({ title: "Unable to save room", description: e.message, variant: "destructive" }) });
  return <Dialog open={open} onOpenChange={v => !v && close()}><DialogContent className="max-w-md rounded-sm"><DialogHeader><DialogTitle>{value ? "Edit room / area" : "Add room / area"}</DialogTitle></DialogHeader><div className="space-y-4"><div><Label>Site *</Label><select className="mt-1 flex h-10 w-full rounded-sm border border-input bg-background px-3 text-sm" value={form.siteId} onChange={e => setForm({ ...form, siteId: e.target.value })}><option value="">Select site</option>{sites.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div><Label>Room number or area *</Label><Input data-testid="input-room-number" className="mt-1" value={form.roomNumber} onChange={e => setForm({ ...form, roomNumber: e.target.value })} placeholder="e.g. 101 or Reception" /></div><div><Label>Area type</Label><Input className="mt-1" value={form.area} onChange={e => setForm({ ...form, area: e.target.value })} placeholder="e.g. guest_room, reception" /></div><div><Label>Equipment template</Label><select data-testid="select-room-template" className="mt-1 flex h-10 w-full rounded-sm border border-input bg-background px-3 text-sm" value={form.templateId} onChange={e => setForm({ ...form, templateId: e.target.value })}><option value="">No template assigned</option>{templates.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></div><div><Label>Test interval (months)</Label><Input className="mt-1" type="number" min="1" value={form.testIntervalMonths} onChange={e => setForm({ ...form, testIntervalMonths: e.target.value })} /></div></div><DialogFooter><Button variant="outline" onClick={close}>Cancel</Button><Button data-testid="button-save-room" disabled={!form.siteId || !form.roomNumber.trim() || mutation.isPending} onClick={() => mutation.mutate()}>{mutation.isPending ? "Saving…" : "Save room"}</Button></DialogFooter></DialogContent></Dialog>;
}

function CertificateDialog({ open, close, value, rooms, sites, selectedSiteId, saved }: { open: boolean; close: () => void; value?: Certificate | null; rooms: Room[]; sites: Site[]; selectedSiteId: string; saved: () => void }) {
  const { toast } = useToast(); const today = new Date().toISOString().slice(0, 10); const [form, setForm] = useState({ siteId: "", testDate: today, contractor: "", certificateRef: "", coveredAreas: "", appliancesTested: "", passCount: "", failCount: "", nextTestDue: "", documentUrl: "" }); const [covered, setCovered] = useState<number[]>([]);
  useEffect(() => { if (open) { setForm({ siteId: value?.siteId ? String(value.siteId) : selectedSiteId, testDate: value?.testDate?.slice(0, 10) ?? today, contractor: value?.contractor ?? "", certificateRef: value?.certificateRef ?? "", coveredAreas: value?.coveredAreas ?? "", appliancesTested: String(value?.appliancesTested ?? ""), passCount: String(value?.passCount ?? ""), failCount: String(value?.failCount ?? ""), nextTestDue: value?.nextTestDue?.slice(0, 10) ?? "", documentUrl: value?.documentUrl ?? "" }); setCovered(value?.coveredRoomIds ?? []); } }, [open, value, today, selectedSiteId]);
  const mutation = useMutation({ mutationFn: () => api(value ? `/certificates/${value.id}` : "/certificates", { method: value ? "PUT" : "POST", body: JSON.stringify({ siteId: Number(form.siteId), visitDate: form.testDate, contractorName: form.contractor.trim() || null, certificateRef: form.certificateRef.trim(), appliancesTestedCount: Number(form.appliancesTested) || 0, passCount: Number(form.passCount) || 0, failCount: Number(form.failCount) || 0, nextTestDue: form.nextTestDue || null, documentLink: form.documentUrl.trim() || null, notes: form.coveredAreas.trim() || null, roomIds: covered }) }), onSuccess: () => { toast({ title: value ? "Certificate updated" : "Certificate recorded" }); saved(); close(); }, onError: (e: Error) => toast({ title: "Unable to save certificate", description: e.message, variant: "destructive" }) });
  return <Dialog open={open} onOpenChange={v => !v && close()}><DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto rounded-sm"><DialogHeader><DialogTitle>{value ? "Edit certificate" : "Record PAT certificate"}</DialogTitle></DialogHeader><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><div><Label>Site *</Label><select className="mt-1 flex h-10 w-full rounded-sm border border-input bg-background px-3 text-sm" value={form.siteId} onChange={e => setForm({ ...form, siteId: e.target.value })}><option value="">Select site</option>{sites.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></div><Field label="Test date *" type="date" value={form.testDate} set={v => setForm({ ...form, testDate: v })}/><Field label="Contractor" value={form.contractor} set={v => setForm({ ...form, contractor: v })}/><Field label="Certificate reference *" value={form.certificateRef} set={v => setForm({ ...form, certificateRef: v })}/><Field label="Next test due" type="date" value={form.nextTestDue} set={v => setForm({ ...form, nextTestDue: v })}/><Field label="Appliances tested" type="number" value={form.appliancesTested} set={v => setForm({ ...form, appliancesTested: v })}/><Field label="Pass count" type="number" value={form.passCount} set={v => setForm({ ...form, passCount: v })}/><Field label="Fail count" type="number" value={form.failCount} set={v => setForm({ ...form, failCount: v })}/><Field label="Document URL" value={form.documentUrl} set={v => setForm({ ...form, documentUrl: v })}/><div className="sm:col-span-2"><Label>Rooms covered</Label><div className="mt-2 grid max-h-32 grid-cols-2 gap-2 overflow-y-auto rounded-sm border p-2 sm:grid-cols-3">{rooms.map(r => <label key={r.id} className="flex items-center gap-2 text-sm"><input data-testid={`checkbox-certificate-room-${r.id}`} type="checkbox" checked={covered.includes(r.id)} onChange={() => setCovered(v => v.includes(r.id) ? v.filter(id => id !== r.id) : [...v, r.id])}/>{r.roomNumber}</label>)}</div></div><div className="sm:col-span-2"><Label>Notes / other covered areas</Label><Textarea className="mt-1" value={form.coveredAreas} onChange={e => setForm({ ...form, coveredAreas: e.target.value })} placeholder="Common areas, plant rooms, etc." /></div></div><DialogFooter><Button variant="outline" onClick={close}>Cancel</Button><Button data-testid="button-save-certificate" disabled={!form.siteId || !form.certificateRef.trim() || mutation.isPending} onClick={() => mutation.mutate()}>{mutation.isPending ? "Saving…" : "Save certificate"}</Button></DialogFooter></DialogContent></Dialog>;
}
function Field({ label, value, set, type = "text" }: { label: string; value: string; set: (v: string) => void; type?: string }) { return <div><Label>{label}</Label><Input className="mt-1" type={type} value={value} onChange={e => set(e.target.value)} /></div>; }

function FailureDialog({ open, close, value, certificates, rooms, saved }: { open: boolean; close: () => void; value?: Failure | null; certificates: Certificate[]; rooms: Room[]; saved: () => void }) {
  const { toast } = useToast(); const [form, setForm] = useState({ certificateId: "", roomId: "", locationText: "", appliance: "", actionTaken: "", resolvedDate: "" });
  useEffect(() => { if (open) setForm({ certificateId: value?.certificateId ? String(value.certificateId) : "", roomId: value?.roomId ? String(value.roomId) : "", locationText: value?.locationText ?? "", appliance: value?.appliance ?? "", actionTaken: value?.actionTaken ?? "", resolvedDate: value?.resolvedDate?.slice(0, 10) ?? "" }); }, [open, value]);
  // Edits re-send the recorded certificate, room and location unchanged; the
  // API rejects any attempt to move a failure or rewrite where it was found.
  const body = () => value ? failureUpdateBody(value, form) : { certificateId: Number(form.certificateId), roomId: form.roomId ? Number(form.roomId) : null, locationText: form.locationText.trim() || null, applianceName: form.appliance.trim(), actionTaken: form.actionTaken.trim() || null, resolvedDate: form.resolvedDate || null };
  const mutation = useMutation({ mutationFn: () => api(value ? `/failures/${value.id}` : "/failures", { method: value ? "PUT" : "POST", body: JSON.stringify(body()) }), onSuccess: () => { toast({ title: value ? "Failure updated" : "Failure recorded" }); saved(); close(); }, onError: (e: Error) => toast({ title: "Unable to save failure", description: e.message, variant: "destructive" }) });
  const recorded = value ? failureLocationDisplay(value) : null;
  const incomplete = !form.appliance.trim() || (!value && (!form.certificateId || (!form.roomId && !form.locationText.trim())));
  return <Dialog open={open} onOpenChange={v => !v && close()}><DialogContent className="max-w-md max-h-[90vh] overflow-y-auto rounded-sm"><DialogHeader><DialogTitle>{value ? "Edit failure" : "Record failed appliance"}</DialogTitle></DialogHeader><div className="space-y-4">{value && recorded ? <div data-testid="failure-recorded-location" className="rounded-sm border bg-muted/40 p-3 text-sm"><p className="font-medium">Certificate {value.certificateRef || value.certificateId} · {recorded.recorded}</p>{recorded.provenance && <p className="mt-1 text-xs text-amber-700">{recorded.provenance}</p>}{recorded.correction && <p className="mt-1 text-xs">{recorded.correction}</p>}<p className="mt-1 text-xs text-muted-foreground">The certificate, room and recorded location are retained evidence and cannot be changed here. An administrator can record a location correction with a reason.</p></div> : <><div><Label>Certificate *</Label><select data-testid="select-failure-certificate" className="mt-1 flex h-10 w-full rounded-sm border border-input bg-background px-3 text-sm" value={form.certificateId} onChange={e => setForm({ ...form, certificateId: e.target.value })}><option value="">Select certificate</option>{certificates.map(c => <option key={c.id} value={c.id}>{c.certificateRef} — {fmt(c.testDate)}</option>)}</select></div><div><Label>Registered room</Label><select className="mt-1 flex h-10 w-full rounded-sm border border-input bg-background px-3 text-sm" value={form.roomId} onChange={e => setForm({ ...form, roomId: e.target.value })}><option value="">Not a registered room</option>{rooms.map(r => <option key={r.id} value={r.id}>{r.roomNumber}</option>)}</select></div><Field label="Location (when not a registered room)" value={form.locationText} set={v => setForm({ ...form, locationText: v })}/></>}<Field label="Appliance *" value={form.appliance} set={v => setForm({ ...form, appliance: v })}/><div><Label>Action taken</Label><Textarea className="mt-1" value={form.actionTaken} onChange={e => setForm({ ...form, actionTaken: e.target.value })} /></div><Field label="Resolved date" type="date" value={form.resolvedDate} set={v => setForm({ ...form, resolvedDate: v })}/></div><DialogFooter><Button variant="outline" onClick={close}>Cancel</Button><Button data-testid="button-save-failure" disabled={incomplete || mutation.isPending} onClick={() => mutation.mutate()}>{mutation.isPending ? "Saving…" : "Save failure"}</Button></DialogFooter></DialogContent></Dialog>;
}

function FailureCorrectionDialog({ value, close, saved }: { value: Failure | null; close: () => void; saved: () => void }) {
  const { toast } = useToast(); const [location, setLocation] = useState(""); const [reason, setReason] = useState("");
  useEffect(() => { if (value) { setLocation(value.correctedLocationText ?? value.locationText ?? ""); setReason(""); } }, [value]);
  const mutation = useMutation({ mutationFn: () => api(`/failures/${value!.id}/location-corrections`, { method: "POST", body: JSON.stringify({ correctedLocationText: location.trim(), reason: reason.trim() }) }), onSuccess: () => { toast({ title: "Location correction recorded" }); saved(); close(); }, onError: (e: Error) => toast({ title: "Unable to record correction", description: e.message, variant: "destructive" }) });
  return <Dialog open={!!value} onOpenChange={v => !v && close()}><DialogContent className="max-w-md rounded-sm"><DialogHeader><DialogTitle>Correct recorded location</DialogTitle></DialogHeader><div className="space-y-4"><p className="text-sm text-muted-foreground">Recorded location: <span className="font-medium text-foreground">{value?.locationText || value?.roomNumber || "None"}</span>. The original stays on the record; this correction is added beside it with your name and reason.</p><Field label="Corrected location *" value={location} set={setLocation}/><div><Label>Reason and evidence *</Label><Textarea data-testid="input-failure-correction-reason" className="mt-1" value={reason} onChange={e => setReason(e.target.value)} placeholder="e.g. Contractor's original sheet lists the boiler room" /></div></div><DialogFooter><Button variant="outline" onClick={close}>Cancel</Button><Button data-testid="button-save-failure-correction" disabled={!location.trim() || reason.trim().length < 3 || mutation.isPending} onClick={() => mutation.mutate()}>{mutation.isPending ? "Saving…" : "Record correction"}</Button></DialogFooter></DialogContent></Dialog>;
}

export default function PATTrackPage() {
  const qc = useQueryClient(); const { toast } = useToast(); const canEdit = useCanEdit(); const [tab, setTab] = useState("overview"); const [siteId, setSiteId] = useState(""); const [template, setTemplate] = useState<EquipmentTemplate | null | undefined>(); const [room, setRoom] = useState<Room | null | undefined>(); const [certificate, setCertificate] = useState<Certificate | null | undefined>(); const [failure, setFailure] = useState<Failure | null | undefined>(); const [correcting, setCorrecting] = useState<Failure | null>(null); const canAdmin = useCanAdmin(); const [replacementRoom, setReplacementRoom] = useState<Room | null>(null); const [replacement, setReplacement] = useState({ appliance: "", replacementAppliance: "", replacedDate: new Date().toISOString().slice(0, 10), notes: "" }); const [deleting, setDeleting] = useState<{ path: string; title: string; queries: string[] } | null>(null);
  const siteSuffix = siteId ? `?siteId=${siteId}` : "";
  const sitesQ = useQuery({ queryKey: key("sites"), queryFn: () => rootApi<Site[]>("/sites") });
  const templatesQ = useQuery({ queryKey: [...key("templates"), siteId], queryFn: async () => readArray(await api<any[]>("/equipment-templates" + siteSuffix)).map(mapTemplate) }); const roomsQ = useQuery({ queryKey: [...key("rooms"), siteId], queryFn: () => api<any[]>("/rooms" + siteSuffix) }); const replacementsQ = useQuery({ queryKey: [...key("replacements"), siteId], queryFn: () => api<any[]>("/replacements" + siteSuffix) }); const certificatesQ = useQuery({ queryKey: [...key("certificates"), siteId], queryFn: async () => readArray(await api<any[]>("/certificates" + siteSuffix)).map(mapCertificate) }); const failuresQ = useQuery({ queryKey: [...key("failures"), siteId], queryFn: async () => readArray(await api<any[]>("/failures" + siteSuffix)).map(mapFailure) }); const overdueQ = useQuery({ queryKey: [...key("overdue"), siteId], queryFn: () => api<any[]>("/overdue-by-room-area" + siteSuffix), enabled: tab === "overview" || tab === "overdue" });
  const sites = readArray(sitesQ.data); const templates = readArray(templatesQ.data), rooms = readArray(roomsQ.data).map(r => mapRoom(r, readArray(replacementsQ.data))), certificates = readArray(certificatesQ.data), failures = readArray(failuresQ.data), overdue: Overdue[] = readArray(overdueQ.data).map((x: any) => ({ id: x.id, roomId: x.id, roomNumber: x.name, area: x.area_type, status: x.status, lastTestDate: x.last_test_date, nextTestDue: x.due_date }));
  const invalidate = (...names: string[]) => names.forEach(name => qc.invalidateQueries({ queryKey: key(name) }));
  const deleteMutation = useMutation({ mutationFn: (path: string) => api(path, { method: "DELETE" }), onSuccess: () => { if (deleting) invalidate(...deleting.queries); toast({ title: "Record deleted" }); setDeleting(null); }, onError: (e: Error) => toast({ title: "Unable to delete record", description: e.message, variant: "destructive" }) });
  const replacementMutation = useMutation({ mutationFn: () => api("/replacements", { method: "POST", body: JSON.stringify({ roomId: replacementRoom!.id, applianceName: replacement.appliance.trim(), replacedOn: replacement.replacedDate, replacementDetails: replacement.replacementAppliance.trim() || null, notes: replacement.notes.trim() || null }) }), onSuccess: () => { toast({ title: "Replacement logged" }); invalidate("rooms", "replacements"); setReplacementRoom(null); }, onError: (e: Error) => toast({ title: "Unable to log replacement", description: e.message, variant: "destructive" }) });
  const stats = useMemo(() => ({ tested: certificates.reduce((n, c) => n + (c.appliancesTested || 0), 0), failed: certificates.reduce((n, c) => n + (c.failCount || 0), 0), open: failures.filter(f => !f.resolvedDate).length, overdueCount: overdue.filter(item => item.status === "overdue").length, untestedCount: overdue.filter(item => item.status === "untested").length }), [certificates, failures, overdue]);
  const renderProblem = (...qs: { error: unknown }[]) => qs.find(q => q.error)?.error;
  return <AppLayout title="PATTrack"><div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6">
    <div className="flex flex-col gap-4 border-b pb-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><Zap className="h-6 w-6 text-amber-500" /><h1 className="text-2xl font-bold tracking-tight">PATTrack</h1></div><p className="mt-1 text-sm text-muted-foreground">Certificate-led compliance plus the original item-by-item appliance testing register.</p></div>{!tab.startsWith("legacy-") && <div className="flex gap-2"><select data-testid="select-pat-site-filter" className="h-10 rounded-sm border border-input bg-background px-3 text-sm" value={siteId} onChange={e => setSiteId(e.target.value)}><option value="">All sites</option>{sites.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select>{canEdit && <Button data-testid="button-add-certificate" onClick={() => setCertificate(null)}><Plus className="mr-1.5 h-4 w-4" />Record certificate</Button>}</div>}</div>
    <div className="flex gap-1 overflow-x-auto border-b" data-testid="tabs-pat-track">{[["overview","Overview"],["overdue","Overdue"],["templates","Templates"],["rooms","Rooms"],["certificates","Certificates"],["failures","Failures"],["legacy-appliances","Legacy appliances"],["legacy-tests","Appliance tests"]].map(([id, label]) => <button data-testid={`tab-${id}`} key={id} onClick={() => setTab(id)} className={`whitespace-nowrap border-b-2 px-3 py-2.5 text-sm font-medium ${tab === id ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground"}`}>{label}{id === "overdue" && (stats.overdueCount + stats.untestedCount) > 0 ? <span className="ml-1.5 inline-flex gap-1 text-xs"><span className="rounded-full bg-rose-100 px-1.5 text-rose-800">{stats.overdueCount} overdue</span><span className="rounded-full bg-amber-100 px-1.5 text-amber-800">{stats.untestedCount} untested</span></span> : null}</button>)}</div>
    {tab === "overview" && <><div className="grid grid-cols-2 gap-3 lg:grid-cols-5">{[[rooms.length,"Rooms / areas",Library,"text-blue-600"],[stats.tested,"Appliances tested",CheckCircle2,"text-emerald-600"],[stats.open,"Open failures",AlertTriangle,"text-rose-600"],[stats.overdueCount,"Overdue",ClipboardList,"text-rose-600"],[stats.untestedCount,"Untested",ClipboardList,"text-amber-600"]].map(([n,l,I,c], i) => { const Icon = I as typeof Library; return <Card key={i} className="rounded-sm"><CardContent className="flex items-center gap-3 p-4"><Icon className={`h-5 w-5 ${c}`} /><div><p className="text-xl font-bold" data-testid={`text-pat-stat-${i}`}>{n as number}</p><p className="text-xs text-muted-foreground">{l as string}</p></div></CardContent></Card>; })}</div><Card className="rounded-sm"><CardContent className="p-5"><h2 className="font-semibold">Register at a glance</h2><p className="mt-1 text-sm text-muted-foreground">{certificates.length ? `${certificates.length} certificate${certificates.length === 1 ? "" : "s"} recorded. ${stats.failed} appliance failure${stats.failed === 1 ? "" : "s"} identified.` : "Start by defining a room template, adding rooms, then recording your contractor’s certificate."}</p></CardContent></Card></>}
    {tab === "overdue" && <ListState query={overdueQ} error={renderProblem(overdueQ)}>{overdue.length ? <div className="space-y-2">{overdue.map((o, i) => <Card key={o.id ?? o.roomId ?? i} className={`${o.status === "untested" ? "border-amber-200" : "border-rose-200"} rounded-sm`}><CardContent className="flex items-center justify-between gap-3 p-4"><div><p className="font-medium">{o.roomNumber ?? o.area ?? "Unspecified area"}</p><p className="text-sm text-muted-foreground">{o.status === "untested" ? "No PAT certificate recorded" : `Next test due: ${fmt(o.nextTestDue)}`}</p></div><Badge className={o.status === "untested" ? "bg-amber-100 text-amber-800 border-amber-200 rounded-sm" : "bg-rose-100 text-rose-800 border-rose-200 rounded-sm"}>{o.status === "untested" ? "Untested" : "Overdue"}</Badge></CardContent></Card>)}</div> : <Empty>No rooms or areas are currently overdue or untested.</Empty>}</ListState>}
    {tab === "templates" && <ListState query={templatesQ} error={renderProblem(templatesQ)}>{templates.length ? <div className="grid gap-3 md:grid-cols-2">{templates.map(t => <Card key={t.id} className="rounded-sm"><CardContent className="p-4"><div className="flex justify-between gap-2"><div><h3 className="font-semibold">{t.name}</h3><p className="text-sm text-muted-foreground">{t.description || "No description"}</p></div><Actions edit={() => setTemplate(t)} remove={() => setDeleting({ path: `/equipment-templates/${t.id}`, title: t.name, queries: ["templates","rooms"] })}/></div><p className="mt-3 text-xs text-muted-foreground">{t.items?.reduce((n, i) => n + (i.quantity || 1), 0) ?? 0} standard appliances</p><div className="mt-2 flex flex-wrap gap-1">{t.items?.slice(0, 6).map((i, x) => <Badge key={x} variant="outline" className="rounded-sm text-xs">{i.name}{i.quantity && i.quantity > 1 ? ` ×${i.quantity}` : ""}</Badge>)}</div></CardContent></Card>)}</div> : <Empty>Create a template to define the equipment standard for a room type.</Empty>}{canEdit && <Button data-testid="button-add-template" className="mt-4" onClick={() => setTemplate(null)}><Plus className="mr-1.5 h-4 w-4" />New template</Button>}</ListState>}
    {tab === "rooms" && <ListState query={roomsQ} error={renderProblem(roomsQ, replacementsQ)}>{rooms.length ? <div className="space-y-2">{rooms.map(r => <Card key={r.id} className="rounded-sm"><CardContent className="p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{r.roomNumber}</h3><p className="text-sm text-muted-foreground">{r.area || "No area"} · {r.templateName || templates.find(t => t.id === r.templateId)?.name || "No template"}</p></div><Actions edit={() => setRoom(r)} remove={() => setDeleting({ path: `/rooms/${r.id}`, title: r.roomNumber, queries: ["rooms","certificates","failures","overdue","replacements"] })}/></div>{r.replacements?.length ? <div className="mt-3 border-t pt-2 text-xs text-muted-foreground">{r.replacements.map(x => { const note = replacementIdentityNote(x, r.roomNumber); return <div key={x.id} className="py-0.5" data-testid={`replacement-${x.id}`}>{x.appliance} → {x.replacementAppliance || "replaced"}{x.replacedDate ? ` · ${fmt(x.replacedDate)}` : ""}{note && <span className="block text-amber-700" data-testid={`replacement-identity-${x.id}`}>{note}</span>}</div>; })}</div> : null}{canEdit && <Button data-testid={`button-add-replacement-${r.id}`} variant="link" size="sm" className="mt-1 h-auto px-0 text-xs" onClick={() => { setReplacementRoom(r); setReplacement({ appliance: "", replacementAppliance: "", replacedDate: new Date().toISOString().slice(0,10), notes: "" }); }}><Wrench className="mr-1 h-3 w-3" />Log replacement</Button>}</CardContent></Card>)}</div> : <Empty>Add every guest room and common area included in your PAT programme.</Empty>}{canEdit && <Button data-testid="button-add-room" className="mt-4" onClick={() => setRoom(null)}><Plus className="mr-1.5 h-4 w-4" />Add room / area</Button>}</ListState>}
    {tab === "certificates" && <ListState query={certificatesQ} error={renderProblem(certificatesQ)}>{certificates.length ? <div className="space-y-2">{certificates.map(c => <Card key={c.id} className="rounded-sm"><CardContent className="flex flex-col justify-between gap-3 p-4 sm:flex-row"><div><div className="flex gap-2"><h3 className="font-semibold">{c.certificateRef}</h3>{c.failCount > 0 && <Badge className="bg-rose-100 text-rose-800 border-rose-200 rounded-sm">{c.failCount} failed</Badge>}</div><p className="text-sm text-muted-foreground">{fmt(c.testDate)} · {c.contractor} · {c.appliancesTested} tested ({c.passCount} pass)</p><p className="mt-1 text-xs text-muted-foreground">Next due: {fmt(c.nextTestDue)} · {c.coveredRoomIds?.length || 0} rooms</p>{c.coveredRooms.length > 0 && <p className="mt-1 text-xs text-muted-foreground">Covered rooms: {c.coveredRooms.map(r => r.name ?? "Historical room name unavailable").join(" · ")}</p>}{c.coveredRooms.some(r => r.snapshotSource === "legacy_backfill") && <p className="mt-1 text-xs text-muted-foreground">Some room names were backfilled from legacy records.</p>}{c.documentUrl && <a data-testid={`link-certificate-document-${c.id}`} className="mt-2 inline-flex text-xs text-primary underline" href={c.documentUrl} target="_blank" rel="noreferrer"><FileText className="mr-1 h-3 w-3" />View document</a>}</div><Actions edit={() => setCertificate(c)}/></CardContent></Card>)}</div> : <Empty>No certificates recorded yet.</Empty>}{canEdit && <Button data-testid="button-add-certificate-bottom" className="mt-4" onClick={() => setCertificate(null)}><Plus className="mr-1.5 h-4 w-4" />Record certificate</Button>}</ListState>}
    {tab === "failures" && <ListState query={failuresQ} error={renderProblem(failuresQ)}>{failures.length ? <div className="space-y-2">{failures.map(f => <Card key={f.id} className="rounded-sm"><CardContent className="flex items-start justify-between gap-3 p-4"><div><div className="flex items-center gap-2"><h3 className="font-semibold">{f.appliance}</h3><Status resolved={f.resolvedDate}/></div>{(() => { const loc = failureLocationDisplay(f); return <><p className="text-sm text-muted-foreground" data-testid={`failure-location-${f.id}`}>{loc.recorded} · Certificate {f.certificateRef || f.certificateId}</p>{loc.provenance && <p className="text-xs text-amber-700">{loc.provenance}</p>}{loc.correction && <p className="text-xs" data-testid={`failure-correction-${f.id}`}>{loc.correction}</p>}{loc.currentRoom && <p className="text-xs text-muted-foreground">{loc.currentRoom}</p>}</>; })()}<p className="mt-1 text-sm">{f.actionTaken || "No action recorded"}</p>{f.resolvedDate && <p className="mt-1 text-xs text-muted-foreground">Resolved {fmt(f.resolvedDate)}</p>}</div><div className="flex shrink-0 flex-col items-end gap-1"><Actions edit={() => setFailure(f)}/>{canAdmin && <Button data-testid={`button-correct-failure-location-${f.id}`} variant="link" size="sm" className="h-auto px-0 text-xs" onClick={() => setCorrecting(f)}>Correct location</Button>}</div></CardContent></Card>)}</div> : <Empty>No appliance failures recorded.</Empty>}{canEdit && <Button data-testid="button-add-failure" className="mt-4" onClick={() => setFailure(null)}><Plus className="mr-1.5 h-4 w-4" />Record failure</Button>}</ListState>}
    {tab === "legacy-appliances" && <LegacyPATRegister view="appliances" />}
    {tab === "legacy-tests" && <LegacyPATRegister view="tests" />}
    <TemplateDialog open={template !== undefined} close={() => setTemplate(undefined)} value={template} sites={sites} selectedSiteId={siteId} saved={() => invalidate("templates","rooms")}/><RoomDialog open={room !== undefined} close={() => setRoom(undefined)} value={room} templates={templates} sites={sites} selectedSiteId={siteId} saved={() => invalidate("rooms","overdue")}/><CertificateDialog open={certificate !== undefined} close={() => setCertificate(undefined)} value={certificate} rooms={rooms} sites={sites} selectedSiteId={siteId} saved={() => invalidate("certificates","overdue")}/><FailureDialog open={failure !== undefined} close={() => setFailure(undefined)} value={failure} certificates={certificates} rooms={rooms} saved={() => invalidate("failures","certificates")}/><FailureCorrectionDialog value={correcting} close={() => setCorrecting(null)} saved={() => invalidate("failures")}/>
    <Dialog open={!!replacementRoom} onOpenChange={v => !v && setReplacementRoom(null)}><DialogContent className="max-w-md rounded-sm"><DialogHeader><DialogTitle>Log appliance replacement — {replacementRoom?.roomNumber}</DialogTitle></DialogHeader><div className="space-y-4"><Field label="Original appliance *" value={replacement.appliance} set={v => setReplacement({ ...replacement, appliance: v })}/><Field label="Replacement appliance" value={replacement.replacementAppliance} set={v => setReplacement({ ...replacement, replacementAppliance: v })}/><Field label="Replacement date" type="date" value={replacement.replacedDate} set={v => setReplacement({ ...replacement, replacedDate: v })}/><div><Label>Notes</Label><Textarea className="mt-1" value={replacement.notes} onChange={e => setReplacement({ ...replacement, notes: e.target.value })}/></div></div><DialogFooter><Button variant="outline" onClick={() => setReplacementRoom(null)}>Cancel</Button><Button disabled={!replacement.appliance.trim() || replacementMutation.isPending} onClick={() => replacementMutation.mutate()}>Save replacement</Button></DialogFooter></DialogContent></Dialog>
    <AlertDialog open={!!deleting} onOpenChange={v => !v && setDeleting(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete {deleting?.title}?</AlertDialogTitle><AlertDialogDescription>This cannot be undone.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction data-testid="button-confirm-delete" className="bg-destructive text-destructive-foreground hover:bg-destructive/90" onClick={e => { e.preventDefault(); if (deleting) deleteMutation.mutate(deleting.path); }}>{deleteMutation.isPending ? "Deleting…" : "Delete"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div></AppLayout>;
}
function ListState({ query, error, children }: { query: { isLoading: boolean }; error?: unknown; children: any }) { if (query.isLoading) return <Loading />; if (error) return <ErrorState error={error} />; return <>{children}</>; }
function Actions({ edit, remove }: { edit: () => void; remove?: () => void }) {
  const canEdit = useCanEdit();
  if (!canEdit) return null;
  return <div className="flex shrink-0 gap-1"><Button data-testid="button-edit-record" variant="ghost" size="icon" className="h-8 w-8" onClick={edit}><Pencil className="h-3.5 w-3.5" /></Button>{remove && <Button data-testid="button-delete-record" variant="ghost" size="icon" className="h-8 w-8 text-destructive" onClick={remove}><Trash2 className="h-3.5 w-3.5" /></Button>}</div>;
}